(source melpa)

(depends-on "ack-and-a-half")
(depends-on "ample-zen-theme")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "color-theme-sanityinc-solarized")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "dash")
(depends-on "enh-ruby-mode")
(depends-on "epl")
(depends-on "f")
(depends-on "grizzl")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")